### ISSUE TITLE
Create an issue and pull request templates

### ISSUE THREAD

**Issue by brenopolanski** [hugopl/reviewit#103]
GitHub now supports **issue templates** via a markdown file called `issue_template.md` in the root or `.github/` folder of your repo!

There is also added support for **pull request** templates via a markdown file called `pull_request_template.md` in the root or `.github/` folder of your repo!

About: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by hugopl** [comment]
Pull requests are done using the web interface in github, on reviewit this is not just impossible by design, since the merge requests are created using the CLI tool and a normal git commit.

reviewit support linters, so you can create such thing in a linter to check if the commit is in the proper format, we use this approach at the company I work on, that I guess is the only company in the world using this tool :-P.
