### ISSUE TITLE
Implement notifications to send updates to apps that puts together work group chats.

### ISSUE THREAD

**Issue by edmilsonefs** [hugopl/reviewit#14]
Below a few example of most known applications that should be considered:
* Campfire,
* Flowdock,
* HipChat,
* Sqwiggle and,
* Slack.

i.e.: A new merge request has been sent. [Click here to see it directly in your browser.]()

**Comment by hugopl** [comment]
Reviewit is not in the same category of those apps, I mean, a reviewit windows isn't mean to be open all the time as e.g. slack is.

So notifications turn to be a bit useless, since isn't possible to a webpage notify the user desktop if it isn't open, besides we already have e-mail notification, so the user will get some notification in the end.
